server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 'validate' trên môi trường production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always   # nếu bạn có file data.sql để insert role mặc định

jwt:
  secret: my_super_long_secret_key_for_auth_service_2025_xyz
  expiration: 3600000           # 1h = 3600000 ms
  refresh-expiration: 604800000 # 7 ngày

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
